name: CI

on: [push]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RACK_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Analyze code
        run: bundle exec rubocop

      - name: Configurar banco de dados
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:prepare

      - name: Rodar RSpec
        run: bundle exec rspec
